config/routes.rb
Rails.application.routes.draw do
  get 'habits/detail'

  resources :habits do
    resources :results
  end

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts

  resources :users
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'habits#index'
  

end

app/models/habit.rb
class Habit < ActiveRecord::Base
  belongs_to :user
  has_many :results

  validates :user_id, presence: true
  validates :target, 
#    presence: { message: "入力してください" },
#	length: { minimum:1, maximum:255, message: "２５５文字以内で入力してください" }
    presence: {  },
	length: { maximum:255 }
#	length: { minimum:1, maximum:255 }
#	length: { :in => 1..255 }
#  validates :start_at, presence: { message: "入力してください" }
  validates :start_at,
#   length: { minimum:10, maximum:10 },
   length: { minimum:10 },
   timeliness: { on_or_before: :end_at, format: '%Y/%m/%d' }
  validates :end_at, 
   length: { minimum:10 },
   timeliness: { on_or_after: :start_at, format: '%Y/%m/%d' }, allow_blank: false
  #validates :end_at , presence: { message: "入力してください" }

#  scope :done, -> { joins(:results).where("result=1") }
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /habits
  # GET /habits.json
  def index
#    @habits = Habit.all
    #@habits = Habit.where(user_id: current_user.id, deleted_at: )
    #@habits = Habit.where("user_id = ? AND deleted_at is null", current_user.id).order('start_at DESC')
#    @habits = Habit.with_deleted.where("user_id = ?", current_user.id).order('start_at DESC')
    @habits = Habit.where("user_id = ?", current_user.id).order('start_at DESC')
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
    #@results = Result.where("habit_id = ?", @habit.id)
    #@results = @habit.results.maximum(result_at)
    #@results = @habit.results.select("strftime('%Y-%m-%d','result_at'),result")
#    logger.warn(@results)
#    logger.warn(@results.maximum('result_at'))

    if params[:month].nil? 
      #logger.warn(params[:month][4..5])
      #@month = Date.today
      #if @month.between?(@habit.start_at, @habit.end_at)
        @month = Date.today
      if @habit.start_at > Date.today
        @month = @habit.start_at
      elsif @habit.end_at < Date.today
        @month = @habit.end_at
      end
    else
      if params[:month].length == 6
        @month = Date.new(params[:month][0..3].to_i, params[:month][4..5].to_i, 1)
      elsif params[:month].length == 10
        #@month = Date.new(params[:month][0..3].to_i, params[:month][5..6].to_i, params[:month][8..9].to_i)
        #@resluts = @habit.results.where("result_at like '%" + params[:month] + "%'")
        @month = Date.parse(params[:month])

        @resluts = @habit.results.where("result_at like '%#{params[:month]}%'")
        if @resluts.count > 0
          #@habit.results.update_all("done = '#{params[:done]}'", "result_at like '%#{params[:month]}%'")
          @habit.results.where("result_at like '%#{params[:month]}%'").update_all(:done => params[:done])
        else    
          @result = Result.new
          @result.habit_id = @habit.id
          @result.done = params[:done].to_i
          @result.result_at = @month
          @result.save
        end

=begin
        if @resluts.count > 0
          @resluts.each do |result|
            #result.done = params[:result].to_i
            #if @habit.update( :results_attributes=>{ :id => result.id, :done => params[:result].to_i })
            logger.warn(params[:done])
            if result.update(:done => params[:done].to_i)
              #format.html { redirect_to @habit, notice: 'Habit was successfully updated.' }
              #format.json { head :no_content }
               logger.warn('更新しました。' + params[:month])
            else
              #format.html { render action: 'edit' }
              #format.json { render json: @habit.errors, status: :unprocessable_entity }
               logger.warn('更新に失敗しました。' + params[:month])
            end
            #logger.warn('result:' + result )            
          end
        else
          #@resluts = result.new          
        end
=end
      end
        
    end
    #@month.between?(@habit.start_at, @habit.end_at) unless  @month = @habit.end_at
    #@month = @habit.end_at unless @month.between?(@habit.start_at, @habit.end_at) 
    #@month = @habit.results.max(result_at)
    @boxs = [[" ", "0"], ["◯", "1"], ["×", "2"], ["—", "3"]]
    @cal_class = ["","cal1","cal2","cal3"]
    @select_class = ["select_result0","select_result1","select_result2","select_result3"]
    @youbiFlg = [@habit.monday, @habit.tuesday, @habit.wednesday, @habit.thursday, @habit.friday, @habit.saturday, @habit.sunday]
    #logger.warn(@habit.results.select(result_at))
    @youbi = @month.beginning_of_month.strftime('%w').to_i
    @youbi = 7 if @youbi == 0
    #@ym = @month.strftime('%Y%m')
    #params.merge(month: @month.beginning_of_month.strftime('%Y%m'))
    @end_day = @month.end_of_month.day
    #@aaa=@habit.results.where("result_at = ?", @month.beginning_of_month+1.day).count
    #@aaa=@habit.results.where(result_at: @month.beginning_of_month..@month.end_of_month).count
    #@aaa=@habit.results.where("result_at like '%" + (@month.beginning_of_month+(3).day).strftime('%Y/%m/%d') + "%'")
    #logger.warn(@month.beginning_of_month)
    #logger.warn(@month.end_of_month)
    #logger.warn(@aaa[0].result)

    #logger.warn(@month.end_of_month.strftime('%d'))
    #Time.now.between?(@habit.start_at, @habit.end_at) unless 
    logger.warn("params#{params}")
  end

  # GET /habits/new
  def new
    @habit = Habit.new
    @habit.user_id = current_user.id
    @habit.start_at = Time.now
    @habit.end_at = Time.now.next_month.yesterday
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits
  # POST /habits.json
  def create
    @habit = Habit.new(habit_params)
    set_checkbox
    respond_to do |format|
      if @habit.save
        format.html { redirect_to @habit, notice: 'Habit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @habit }
      else
        format.html { render action: 'new' }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1
  # PATCH/PUT /habits/1.json
  def update
    respond_to do |format|
      ##@habit.sunday = habit_params[sunday]
      #@habit.monday = habit_params[monday]
      #if params['sunday'].nil? 
      #  @habit.sunday = false
      #else
      #  @habit.sunday = true
      #end
      set_checkbox
      #logger.warn(params['sunday'])
      #logger.warn(params['monday'])
#      config.debag_logger.debag(params)
      #@habit.target = @habit.target + params['sunday'].to_s
      #logger.warn(params['habit'])
      logger.warn(params['habit'].require(:start_at).length)
      if @habit.update(habit_params)
        format.html { redirect_to @habit, notice: 'Habit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to habits_url }
      #format.json { head :no_content }
    end
  end

  # GET /habits/1
  # GET /habits/1.json
  def detail
    logger.warn(params)
    #redirect_to habit_result_path
  end

def update_result
      logger.warn('update_result')  
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def habit_params
#      params.require(:habit).permit(:user_id, :target, :start_at, :end_at)
      params.require(:habit).permit(:target, :start_at, :end_at, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :results_attributes)
#      params[:habit].permit(:target, :start_at, :end_at, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    def result_params
#      params.require(:habit).permit(:user_id, :target, :start_at, :end_at)
      params.require(:result).permit(:done)
#      params[:habit].permit(:target, :start_at, :end_at, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday)
    end

    # Before actions
    def signed_in_user
      #redirect_to signin_url, notice: "Please sign in." unless signed_in?
      unless signed_in?
        store_location
        flash[:warning] = "Please sign in."
        redirect_to signin_url
      end
    end

    def set_checkbox
      logger.warn('set_checkbox')
      if params['sunday'].nil? 
        @habit.sunday = false
      else
        @habit.sunday = true
      end
      if params['monday'].nil? 
        @habit.monday = false
      else
        @habit.monday = true
      end
      if params['tuesday'].nil? 
        @habit.tuesday = false
      else
        @habit.tuesday = true
      end
      if params['wednesday'].nil? 
        @habit.wednesday = false
      else
        @habit.wednesday = true
      end
      if params['thursday'].nil? 
        @habit.thursday = false
      else
        @habit.thursday = true
      end
      if params['friday'].nil? 
        @habit.friday = false
      else
        @habit.friday = true
      end
      if params['saturday'].nil? 
        @habit.saturday = false
      else
        @habit.saturday = true
      end
      #logger.warn(@habit.sunday)
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/detail.html.erb
<h1>Habits#detail</h1>
<p>Find me in app/views/habits/detail.html.erb</p>

<script>
  
  
  $(document).ready(function(){
      // page is now ready, initialize the calendar...
      $('#calendar').fullCalendar({
          editable: true,
          header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
          },
          defaultView: 'agendaWeek',
          height: 500,
          slotMinutes: 15,
          loading: function(bool){
              if (bool) 
                  $('#loading').show();
              else 
                  $('#loading').hide();
          },
          events: "/events/get_events",
          timeFormat: 'h:mm t{ - h:mm t} ',
          dragOpacity: "0.5",
          eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
              //if (confirm("Are you sure about this change?")) {
                  moveEvent(event, dayDelta, minuteDelta, allDay);
              //}
              //else {
              //    revertFunc();
              //}
          },
          
          eventResize: function(event, dayDelta, minuteDelta, revertFunc){
              //if (confirm("Are you sure about this change?")) {
                  resizeEvent(event, dayDelta, minuteDelta);
              //}
              //else {
              //    revertFunc();
              //}
          },
          
          eventClick: function(event, jsEvent, view){
              showEventDetails(event);
          },
      
      
      
      
      });
  });
</script>
<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>

app/views/habits/edit.html.erb
<h1>目標編集</h1>

<%= render 'form' %>

<!--
<%= link_to 'Show', @habit %> |
<%= link_to 'Back', habits_path %>
-->

<!--
<%= button_to '詳細', @habit, :method => :get, :class => "btn btn-primary" %>
<%= button_to '一覧に戻る', habits_path, :method => :get %>
-->

app/views/habits/index.html.erb
<h1>目標一覧</h1>

<table class="index_list">
  <thead>
    <tr text-align="center" valign="middle">
      <!--<th>User</th>-->
      <th Width="500px">目標</th>
      <th Width="100px">開始日</th>
      <th Width="100px">終了日</th>
      <th Width="80px">実行日数</th>
      <!--<th Width="80px">未実行日数</th>-->
      <!--<th Width="80px">対象外日数</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <!--<td><%= habit.user_id %></td>-->
        <td class="title"><%= habit.target %></td>
        <td><%= habit.start_at.strftime('%Y/%m/%d') %></td>
        <td><%= habit.end_at.strftime('%Y/%m/%d') %></td>
        <!--<td><%= link_to 'Show', habit %></td>-->
        <!--<td><%= link_to 'Edit', edit_habit_path(habit) %></td>-->
        <!--<td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <td><%= habit.results.where('done=1').count %> / <%= habit.results.where('done<3').count %></td>
        <!--<td><%= 0 %></td>-->
        <!--<td><%= 0 %></td>-->
        <td Width="100px"><%= button_to '詳細', habit, :method => :get, :class => "button_show button_list" %></td>
        <td Width="100px"><%= button_to '編集', edit_habit_path(habit), :method => :get, :class => "button_edit button_list" %></td>
        <td Width="100px"><%= button_to '削除', habit, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button_delete button_list" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="center">
<%= button_to '新規登録', new_habit_path, :method => :get, :class => "button_edit button_lg" %>
</div>

<!--
<%= link_to 'New Habit', new_habit_path %>
-->
 

app/views/habits/new.html.erb
<h1>新規目標登録</h1>

<%= render 'form' %>

<!--
<%= link_to '一覧に戻る', habits_path %>
-->

app/views/habits/show.html.erb
<p id="notice"><%= notice %></p>
<h1>目標:<%= @habit.target %></h1>
<h2>期間:<%= @habit.start_at.strftime('%Y/%m/%d') %> 〜 <%= @habit.end_at.strftime('%Y/%m/%d') %></h2>
<h2>対象曜日:
	<% if @habit.monday %><%= '月 ' %><% end %>
	<% if @habit.tuesday %><%= '火 ' %><% end %>
	<% if @habit.wednesday %><%= '水 ' %><% end %>
	<% if @habit.thursday %><%= '木 ' %><% end %>
	<% if @habit.friday %><%= '金 ' %><% end %>
	<% if @habit.saturday %><%= '土' %><% end %>
  <% if @habit.sunday %><%= '日 ' %><% end %>
</h2>

<!--
<h2><%= @month.strftime('%Y/%m/%d')  %></h2>
<div id="calendar"></div>
-->
<% if false %>
 <%= button_to '＜', "", :id => "last_month" , :method => :get, :class => "button_lg", :name => @month.next_month.strftime('%Y%m') %>

  <%= button_to '＞', {controller:"habits", action:"show",id:@habit.id, month:@month.next_month.strftime('%Y%m')}, :id => "next_month" , :method => :get, :class => "button_lg" %>
<%= link_to('先月','#', :method => :get, :data=> @month.last_month) -%>
<% end %>

<div style="text-align: center">
<% if @month.last_month.beginning_of_month.between?(@habit.start_at,@habit.end_at) or @month.last_month.end_of_month.between?(@habit.start_at,@habit.end_at) %>
<%= link_to "＜", {controller:"habits", action:"show",id:@habit.id, month:@month.last_month.beginning_of_month.strftime('%Y%m')}, :method => :get, :class => "link_month" %>
<% else %>
<%= link_to_unless_current("＜", {:controller => "habits", :action => "show"}) do
    link_to("＜", {:controller => "habits", :action => "show"},  :class => "link_month disabled")
  end %>
<% end %>
<%= label :month, @month.strftime('%Y/%m'), '', :class => 'this_month' %>
<% if @month.next_month.beginning_of_month.between?(@habit.start_at,@habit.end_at) or @month.next_month.end_of_month.between?(@habit.start_at,@habit.end_at) %>
<%= link_to "＞", {controller:"habits", action:"show",id:@habit.id, month:@month.next_month.strftime('%Y%m')}, :method => :get, :class => "link_month"  %>
<% else %>
<%= link_to_unless_current("＞", {:controller => "habits", :action => "show"}) do
    link_to("＞", {:controller => "habits", :action => "show"},  :class => "link_month disabled")
  end %>
<% end %>


<%#= label :page, "＞", '', :class => 'disabled_month' %>
<%#= link_to_unless_current("＞", {:controller => "habits", :action => "show"}, :class => "disabled_month")  %>

<%#= link_to_unless_current("＞", {:controller => "habits", :action => "show"},  :class => "disabled_month") do
    link_to("＞", {:controller => "habits", :action => "show"},  :class => "disabled_month disabled")
  end
%>



</div>
<br>
<table  class="index_list" width="100%">
  <thead>
    <tr text-align="center" valign="middle">
      <!--<th>User</th>-->
      <th>月</th>
      <th>火</th>
      <th>水</th>
      <th>木</th>
      <th>金</th>
      <th>土</th>
      <th>日</th>
    </tr>
  </thead>
 <tbody>
<% date = 0 %>
<% if false %>
<% youbi = 7 %>
<% date = num + (num * (row - 1)) %>
<% date = youbi + (num * (row - 1)) %>
<% end %>

<% for row in 1..6 do %>
<% if date >= @month.end_of_month.day %>
<% break %>
<% end %>

      <tr>
<% for num in 1..7 do %>
  <% if date.between?(1,@month.end_of_month.day-1) or (num == @youbi and date == 0) %>
    <% date += 1 %>
    <% today = (@month.beginning_of_month+(date-1).day).strftime('%Y-%m-%d') %>
    <% reslut = @habit.results.where("result_at like '%#{today}%'") %>
    <% if reslut.count > 0  %>
      <td id=<%= "td#{reslut[0].result_at.strftime('%Y-%m-%d')}" %> class=<%= @cal_class[reslut[0].done] %> >
        <%= select_tag reslut[0].result_at.strftime('%Y-%m-%d'), options_for_select(@boxs, :selected => reslut[0].done), { class: @select_class[reslut[0].done] }  %>
        <%= date %><br>
    <% elsif @youbiFlg[num-1] and today >= @habit.start_at.beginning_of_day and today <= @habit.end_at.end_of_day %>
      <td id=<%= "td#{today}" %> class="cal_com">
        <%= select_tag today, options_for_select(@boxs, :selected => "0" ), { class: "select_result0" } %><%= date %>
    <% elsif today < @habit.start_at.beginning_of_day or today > @habit.end_at.end_of_day %>
      <td id=<%= "td#{today}" %> class="no_cal">
        <%= select_tag today, options_for_select(@boxs, :selected => "0" ), { class: "select_disabled", disabled: true  } %><%= date %>
    <% else %>
      <td id=<%= "td#{today}" %> class="cal3">
        <%= select_tag today, options_for_select(@boxs, :selected => "3" ), { class: "select_result3" } %>
        <%= date %><br>
    <% end %>
  <% else %>
    <td class="no_cal"><br>
  <% end %>
    </td>
<% end %>
      </tr>
<% end %>

  </tbody>
</table>  
  <div class="center">
  <%= button_to '編集', edit_habit_path(@habit), :method => :get, :class => "button_edit button_lg" %>
  <%= button_to '一覧に戻る', habits_path, :method => :get, :class => "button_back" %>
  </div>

<% if false %>
    <% @habit.results.each do |result| %>
      <tr>
        <td><%= result.result_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td>
        <ul class="nav navbar-nav">
            <li id="fat-menu" class="dropdown">
              <a href="#" data-toggle="dropdown"><%= result.done %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to " ", new_habit_path %></li>
                <li class="divider"></li>
                <li><%= link_to "○", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "×", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "−", signout_path %></li>
              </ul>
            </li>
        </ul>
<select id="year_select" name="y" style="width:100px;">
                <option value="0"> </option>
                <option value="1">○</option>
                <option value="2">×</option>
                <option value="3">−</option>
</select>
        </td>
      </tr>
    <% end %>


<p>
  <strong>User:</strong>
  <%= @habit.user_id %>
  <%= current_user.name %>
</p>

<p>
  <strong>Target:</strong>
  <%= @habit.target %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @habit.start_at.strftime('%Y/%m/%d') %>
</p>

<p>
  <strong>End at:</strong>
  <%= @habit.end_at.strftime('%Y/%m/%d') %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>
<% end %>

<script>
$(function(){
  function next_month(date){
  }
  $("select").change(function() {
    //alert("クリックしました");
    //alert(this);
    //alert(this.className);
    var flg = false;
    flg = $.ajax({
      //url: "detail/",
      type: "GET",
      data: { month : this.name,
              done: this.value,
      },
      success: function(data) {
          //alert("success");
          //window.location.reload(); 
      },
      error: function(data) {
          alert("更新に失敗にしました．");
      }
    });
    if (flg) {
      var cal_class = ["","cal1","cal2","cal3"];
      var select_class = ["select_result0","select_result1","select_result2","select_result3"];
      this.className = select_class[this.value];
      var elem = document.getElementById("td"+this.name);
      elem.className = cal_class[this.value];
    }
  });
/*
$("#last_month").click(function() {
    //alert("クリックしました");
    alert(this.name);

    $.ajax({
            //url: "habits/",
            type: "GET",
            data: {month : this.name,
                    //id: 2,
                    //mode: 'hoge',
                    //type: 'entry'
                    },
            //dataType: "html",
            success: function(data) {
                alert("success");
            },
            error: function(data) {
                alert("errror");
            }
    });
    return false;
  });
  $("input[name=next_month]").click(function(){ 
alert("next_month");
  });
*/
});

</script>